### ISSUE TITLE
unable to sign in after starting project locally with .env completely setup for sandbox

### ISSUE THREAD

**Issue by Thebanker666** [fotinh0/foti-banking-app#1]
platinum@PLATINUMs-MacBook-Air foti-banking-app-main % npm run dev

> jsm_banking@0.1.0 dev
> next dev

  ▲ Next.js 14.2.3
  - Local:        http://localhost:3000
  - Environments: .env

 ✓ Starting...
 ✓ Ready in 2.3s
 ○ Compiling /sign-in ...
 ✓ Compiled /sign-in in 2.9s (1657 modules)
 ✓ Compiled in 203ms (581 modules)
SyntaxError: "undefined" is not valid JSON
    at JSON.parse (<anonymous>)
    at parseStringify (webpack-internal:///(action-browser)/./lib/utils.ts:73:38)
    at $$ACTION_0 (webpack-internal:///(action-browser)/./lib/actions/user.actions.ts:57:70)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async $$ACTION_1 (webpack-internal:///(action-browser)/./lib/actions/user.actions.ts:73:22)
    at async /Users/platinum/Movies/foti-banking-app-main/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:39:418
    at async rS (/Users/platinum/Movies/foti-banking-app-main/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:38:7978)
    at async r2 (/Users/platinum/Movies/foti-banking-app-main/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:41:1251)
    at async doRender (/Users/platinum/Movies/foti-banking-app-main/node_modules/next/dist/server/base-server.js:1438:30)
    at async cacheEntry.responseCache.get.routeKind (/Users/platinum/Movies/foti-banking-app-main/node_modules/next/dist/server/base-server.js:1599:28)
    at async DevServer.renderToResponseWithComponentsImpl (/Users/platinum/Movies/foti-banking-app-main/node_modules/next/dist/server/base-server.js:1507:28)
    at async DevServer.renderPageComponent (/Users/platinum/Movies/foti-banking-app-main/node_modules/next/dist/server/base-server.js:1924:24)
    at async DevServer.renderToResponseImpl (/Users/platinum/Movies/foti-banking-app-main/node_modules/next/dist/server/base-server.js:1962:32)
    at async DevServer.pipeImpl (/Users/platinum/Movies/foti-banking-app-main/node_modules/next/dist/server/base-server.js:920:25)
    at async NextNodeServer.handleCatchallRenderRequest (/Users/platinum/Movies/foti-banking-app-main/node_modules/next/dist/server/next-server.js:272:17)
    at async DevServer.handleRequestImpl (/Users/platinum/Movies/foti-banking-app-main/node_modules/next/dist/server/base-server.js:816:17)
    at async /Users/platinum/Movies/foti-banking-app-main/node_modules/next/dist/server/dev/next-dev-server.js:339:20
    at async Span.traceAsyncFn (/Users/platinum/Movies/foti-banking-app-main/node_modules/next/dist/trace/trace.js:154:20)
    at async DevServer.handleRequest (/Users/platinum/Movies/foti-banking-app-main/node_modules/next/dist/server/dev/next-dev-server.js:336:24)
    at async invokeRender (/Users/platinum/Movies/foti-banking-app-main/node_modules/next/dist/server/lib/router-server.js:174:21)
    at async handleRequest (/Users/platinum/Movies/foti-banking-app-main/node_modules/next/dist/server/lib/router-server.js:353:24)
    at async requestHandlerImpl (/Users/platinum/Movies/foti-banking-app-main/node_modules/next/dist/server/lib/router-server.js:377:13)
    at async Server.requestListener (/Users/platinum/Movies/foti-banking-app-main/node_modules/next/dist/server/lib/start-server.js:141:13)
Error SyntaxError: "undefined" is not valid JSON
    at JSON.parse (<anonymous>)
    at parseStringify (webpack-internal:///(action-browser)/./lib/utils.ts:73:38)
    at $$ACTION_1 (webpack-internal:///(action-browser)/./lib/actions/user.actions.ts:76:70)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /Users/platinum/Movies/foti-banking-app-main/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:39:418
    at async rS (/Users/platinum/Movies/foti-banking-app-main/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:38:7978)
    at async r2 (/Users/platinum/Movies/foti-banking-app-main/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:41:1251)
    at async doRender (/Users/platinum/Movies/foti-banking-app-main/node_modules/next/dist/server/base-server.js:1438:30)
    at async cacheEntry.responseCache.get.routeKind (/Users/platinum/Movies/foti-banking-app-main/node_modules/next/dist/server/base-server.js:1599:28)
    at async DevServer.renderToResponseWithComponentsImpl (/Users/platinum/Movies/foti-banking-app-main/node_modules/next/dist/server/base-server.js:1507:28)
    at async DevServer.renderPageComponent (/Users/platinum/Movies/foti-banking-app-main/node_modules/next/dist/server/base-server.js:1924:24)
    at async DevServer.renderToResponseImpl (/Users/platinum/Movies/foti-banking-app-main/node_modules/next/dist/server/base-server.js:1962:32)
    at async DevServer.pipeImpl (/Users/platinum/Movies/foti-banking-app-main/node_modules/next/dist/server/base-server.js:920:25)
    at async NextNodeServer.handleCatchallRenderRequest (/Users/platinum/Movies/foti-banking-app-main/node_modules/next/dist/server/next-server.js:272:17)
    at async DevServer.handleRequestImpl (/Users/platinum/Movies/foti-banking-app-main/node_modules/next/dist/server/base-server.js:816:17)
    at async /Users/platinum/Movies/foti-banking-app-main/node_modules/next/dist/server/dev/next-dev-server.js:339:20
    at async Span.traceAsyncFn (/Users/platinum/Movies/foti-banking-app-main/node_modules/next/dist/trace/trace.js:154:20)
    at async DevServer.handleRequest (/Users/platinum/Movies/foti-banking-app-main/node_modules/next/dist/server/dev/next-dev-server.js:336:24)
    at async invokeRender (/Users/platinum/Movies/foti-banking-app-main/node_modules/next/dist/server/lib/router-server.js:174:21)
    at async handleRequest (/Users/platinum/Movies/foti-banking-app-main/node_modules/next/dist/server/lib/router-server.js:353:24)
    at async requestHandlerImpl (/Users/platinum/Movies/foti-banking-app-main/node_modules/next/dist/server/lib/router-server.js:377:13)
    at async Server.requestListener (/Users/platinum/Movies/foti-banking-app-main/node_modules/next/dist/server/lib/start-server.js:141:13)
 POST /sign-in 200 in 7748ms

**Comment by khanareeb17** [comment]
@Thebanker666 Did you find any thing?
